services:
  mysql:
    image: mysql:latest
    container_name: test-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-test_db}
      MYSQL_USER: ${MYSQL_USER:-test_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-1234}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
  restart: unless-stopped

  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app-container
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      SECRET: ${SECRET}
    ports:
      - "8100:8100"
    restart: unless-stopped

volumes:
  mysql-data: