services:
  test-mysql-container:
    image: mysql:8.0
    container_name: test-mysql-container
    env_file: 
      - .env.docker
    ports:
      - "3307:3306"  # Changed external port to 3307
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD || exit 1"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5

  go-app:
    build:
      context: .
      network: host
    container_name: go-app-container
    ports:
      - "8100:8100"
    depends_on:
      test-mysql-container:
        condition: service_healthy
    env_file: 
      - .env.docker

volumes:
  mysql-data: