CREATE TABLE IF NOT EXISTS payment(
payment_id BIGINT PRIMARY KEY AUTO_INCREMENT,
order_id BIGINT NOT NULL,
total FLOAT NOT NULL,
mode VARCHAR(255) NOT NULL,
status BOOLEAN NOT NULL,
FOREIGN KEY(order_id) REFERENCES Orders(order_id)
);