CREATE TABLE IF NOT EXISTS User(
user_id BIGINT PRIMARY KEY AUTO_INCREMENT,
role ENUM('customer', 'chef', 'admin') NOT NULL,
name VARCHAR(255) NOT NULL,
mobile_number BIGINT,
email VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL
);